[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
migration = { path = "../../migration" }
libs = { path = "../libs", features = ["redis"] }
chrono.workspace = true
redis.workspace = true
sea-orm.workspace = true
serde.workspace = true
