[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
application = { path = "../application" }
async-trait.workspace = true
axum.workspace = true
libs = { path = "../libs" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
validator.workspace = true
utoipa.workspace = true
utoipa-scalar.workspace = true
futures = "0.3"
