[package]
name = "server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rust-backend-playground"
path = "src/main.rs"

[dependencies]
api = { path = "../api" }
application = { path = "../application" }
async-trait.workspace = true
infrastructure = { path = "../infrastructure" }
libs = { path = "../libs", features = ["telemetry"] }
axum.workspace = true
dotenvy.workspace = true
tokio.workspace = true
tracing.workspace = true
